version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    networks:
      - prestashop_net

  prestashop:
    image: prestashop/prestashop:latest
    environment:
      - DB_SERVER=mysql
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - PS_DOMAIN=localhost
      - PS_INSTALL_AUTO=1
    ports:
      - "8080:80"
    networks:
      - prestashop_net
    depends_on:
      - mysql

networks:
  prestashop_net:
