global:
  checkNewVersion: false
  sendAnonymousUsage: false

# log:
#   level: DEBUG

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic

entryPoints:
  http:
    address: :80
  https:
    address: :443
  metrics:
    address: :8082

certificatesResolvers:
  le:
    acme:
      email: test@test.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
