global:
  resolve_timeout: 5m
  smtp_smarthost: "ps-smtp:25"
  smtp_from: "alertmanager@prestashop.local"
  smtp_require_tls: false

templates:
  - "/etc/alertmanager/template/*.tmpl"

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "email-notifications"
  routes:
    - match:
        severity: critical
      receiver: "email-notifications"
      repeat_interval: 15m
    - match:
        severity: warning
      receiver: "slack-notifications"
      repeat_interval: 30m

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "admin@prestashop.local"
        send_resolved: true

  - name: "slack-notifications"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/REPLACE_WITH_YOUR_WEBHOOK_URL"
        channel: "#monitoring-alerts"
        send_resolved: true
        title: "{{ .GroupLabels.alertname }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
