global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL}
  evaluation_interval: ${PROMETHEUS_EVAL_INTERVAL}
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:${NODE_EXPORTER_PORT}"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:${CADVISOR_PORT}"]

  - job_name: "prestashop"
    metrics_path: /metrics
    static_configs:
      - targets: ["prestashop:80"]
