services:
  prestashop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-prestashop
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - prestashop_data:/var/www/html
    networks:
      - traefik
      - backend

volumes:
  prestashop_data:
  mysql_data:
  backup_data:
  prometheus_data:
  grafana_data:

networks:
  traefik:
    driver: ${TRAEFIK_NETWORK}
    external: true
    name: ${TRAEFIK_NETWORK}
  backend:
    driver: bridge
    internal: true
    external: true
